use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchOrderResult {
    code: String,
    data: Vec<SpotDatum>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpotData {
    /// The user self-defined order id.
    pub client_oid: String,
    /// The unique order id generated by the trading system,which can be used later for further
    /// actions such as canceling the order.
    pub order_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpotDatum {
    /// The user self-defined order ID.
    pub client_oid: Option<String>,
    /// Error message
    pub fail_msg: Option<String>,
    /// The unique order ID generated by the trading system, which can be used later for further
    /// actions such as canceling the order.
    pub order_id: Option<String>,
    /// Add order success/failure
    pub success: bool,
}
