// Example code that deserializes and serializes the model.
// extern crate serde;
// #[macro_use]
// extern crate serde_derive;
// extern crate serde_json;
//
// use generated_module::Model;
//
// fn main() {
//     let json = r#"{"answer": 42}"#;
//     let model: Model = serde_json::from_str(&json).unwrap();
// }

use serde::{Deserialize, Serialize};

/// Cancel Partial Order for Spot request.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpotQuery {
    /// The unique order id generated by the trading system
    pub order_id: String,
    /// The size you want cancel
    pub cancel_size: String,
    /// symbol
    pub symbol: String,
}
